
AUDIO_FILE = 'audioFile'
AUDIO_START = 'audioStart'
AUDIO_STOP = 'audioStop'
AUTHOR = 'author'
TRANSLATIONS = 'translations'
CHAPTERS = 'chapters'
FIRST_LINE = 'firstLine'
LAST_LINE = 'lastLine'
TITLE = 'title'
URL = 'url'
IDX = 'idx'
